<a href="https://colab.research.google.com/github/shreyas1209/Sudoku_Solver_App/blob/main/sudoku_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
import sys

sys.path.append('/content/gdrive/MyDrive/Sudoku/Models')
sys.path.append('/content/gdrive/MyDrive/Sudoku')

In [3]:
from sudoku_solver import *

In [13]:
sample_sudoku = np.array(
    [[8,0,0,0,1,0,0,0,9],
     [0,5,0,8,0,7,0,1,0],
     [0,0,4,0,9,0,7,0,0],
     [0,6,0,7,0,1,0,2,0],
     [5,0,8,0,6,0,1,0,7],
     [0,1,0,5,0,2,0,9,0],
     [0,0,7,0,4,0,6,0,0],
     [0,8,0,3,0,9,0,4,0],
     [3,0,0,0,5,0,0,0,8]]
)
sample_sudoku1 = np.array(
    [[8,5,0,0,0,2,4,0,0],
     [7,2,0,0,0,0,0,0,9],
     [0,0,4,0,0,0,0,0,0],
     [0,0,0,1,0,7,0,0,2],
     [3,0,5,0,0,0,9,0,0],
     [0,4,0,0,0,0,0,0,0],
     [0,0,0,0,8,0,0,7,0],
     [0,1,7,0,0,0,0,0,0],
     [0,0,0,0,3,6,0,4,0]]
)




In [14]:
output = solve_sudoku(sample_sudoku)
if(output[0]==True):
  print(output[1])



[[8 7 2 4 1 3 5 6 9]
 [9 5 6 8 2 7 3 1 4]
 [1 3 4 6 9 5 7 8 2]
 [4 6 9 7 3 1 8 2 5]
 [5 2 8 9 6 4 1 3 7]
 [7 1 3 5 8 2 4 9 6]
 [2 9 7 1 4 8 6 5 3]
 [6 8 5 3 7 9 2 4 1]
 [3 4 1 2 5 6 9 7 8]]


In [15]:
output1 = solve_sudoku(sample_sudoku1)
if(output1[0]==True):
  print(output1[1])

[[8 5 9 6 1 2 4 3 7]
 [7 2 3 8 5 4 1 6 9]
 [1 6 4 3 7 9 5 2 8]
 [9 8 6 1 4 7 3 5 2]
 [3 7 5 2 6 8 9 1 4]
 [2 4 1 5 9 3 7 8 6]
 [4 3 2 9 8 1 6 7 5]
 [6 1 7 4 2 5 8 9 3]
 [5 9 8 7 3 6 2 4 1]]
